---

- hosts: all
  become: true
  tasks:

  - name: install httpd package
    yum:
      name: httpd
      state: latest

  - name: install iotop package
    yum:
      name: iotop
      state: latest

  - name: install apache2
    yum:
      name: apache2
      state: latest
    when: ansible_distribution == "Amazon"
